name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-all:
    runs-on: [self-hosted, Linux, ARM64]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: "extra-experimental-features = nix-command flakes"
      - name: Run unit + integration tests
        run: nix run .#test-all

  test-e2e:
    runs-on: [self-hosted, Linux, ARM64]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: "extra-experimental-features = nix-command flakes"
      - name: Run end-to-end browser tests
        run: nix run .#test-e2e
